services:
  nextjs-app:
    build: ./hello-next
    ports:
      - "3001:3000"
    volumes:
      - ./hello-next:/app
      - /app/node_modules
    depends_on:
      - nest-api
    environment:
      - NODE_ENV=development

  nest-api:
    build: ./nest-api
    ports:
      - "4000:3000"
    volumes:
      - ./nest-api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
